### ISSUE TITLE
ImportError: cannot import name 'force_text' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by zoullou** [benkonrath/django-csv-export-view#15]
Hello,

I see in main branch that "force_text" usage was replaced by "force_str" but the last version of this package don't include this change and "force_text" was removed from Django 4. So could you release a new version with last fixes to allow use use this package with Django 4.

Thanks

**Comment by benkonrath** [comment]
Thanks for letting me know. I'll try to make a new release this week sometime.

**Comment by benkonrath** [comment]
I just released 2.0.0 with the fixes.
