### ISSUE TITLE
Narrow csv output

### ISSUE THREAD

**Issue by szabozoltan69** [benkonrath/django-csv-export-view#21]
Is there an option to have the opportunity to keep "multiple values" in the same column?
Most of csv renderers flatten such multiplications, so create new columns for them, but it would be fine to have the opportunity to keep the column structure and repeat rows instead (with iterating the multiple values in the same column). 
An example: for a, b, (c, d, e), f:
a b c f
a b d f
a b e f
would be the result. Is it possible to do this?

**Comment by benkonrath** [comment]
I'm closing this issue. Please reopen it if you have more to add.
