### ISSUE TITLE
Documentation - in README.md, include import path in example code

### ISSUE THREAD

**Issue by cudevmaxwell** [benkonrath/django-csv-export-view#6]
While the rest of the documentation in the README is very good, it would be helpful if the import path was included, as `from csv_export.views import CSVExportView` isn't totally obvious.

**Comment by benkonrath** [comment]
Fixed by https://github.com/benkonrath/django-csv-export-view/commit/d60ee690205c5b84c1b2e8dc8d674816335c039d
