### ISSUE TITLE
Django 3.0 compatibility - Use six instead of django.utils.six 

### ISSUE THREAD

**Issue by cudevmaxwell** [benkonrath/django-csv-export-view#7]
The [Django 3.0 Release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) mention that importing `django.utils.six` is no longer supported, and instead https://pypi.org/project/six/ should be used directly.

**Comment by benkonrath** [comment]
Fixed by #9
